@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

AddressBook *-right-> "1" UniqueCompanyList

UniqueCompanyList -right-> InternshipApplication

InternshipApplication *--> CompanyName
InternshipApplication *--> JobType
InternshipApplication *--> Email
InternshipApplication *--> Description
InternshipApplication *--> ApplicationStatus
InternshipApplication *--> Deadline
InternshipApplication *--> Industry
@enduml
