@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyAddressBook" as ReadOnlyAddressBook
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class AddressBook
Class ModelManager
Class UserPrefs

Class UniqueCompanyList
Class InternshipApplication
Class CompanyName
Class JobType
Class Email
Class Description
Class ApplicationStatus
Class Deadline
Class Industry

Class I #FFFFFF
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

AddressBook .up.|> ReadOnlyAddressBook

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyAddressBook
ModelManager -left-> "1" AddressBook
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

AddressBook *--> "1" UniqueCompanyList
UniqueCompanyList --> "~* all" InternshipApplication
InternshipApplication *--> CompanyName
InternshipApplication *--> JobType
InternshipApplication *--> Email
InternshipApplication *--> Description
InternshipApplication *--> ApplicationStatus
InternshipApplication *--> Deadline
InternshipApplication *--> Industry

InternshipApplication -[hidden]up--> I
UniqueCompanyList -[hidden]right-> I

CompanyName -[hidden]right-> JobType
JobType -[hidden]right-> Email
Email -[hidden]right-> Description
Description -[hidden]right-> ApplicationStatus
ApplicationStatus -[hidden]right-> Deadline
Deadline -[hidden]right-> Industry

ModelManager --> "~* filtered" InternshipApplication
@enduml
